services:
  backend:
    build: ./backend
    container_name: drone-delivery-backend
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    restart: unless-stopped

  user:
    build: ./user
    container_name: drone-delivery-user
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

  admin:
    build: ./admin
    container_name: drone-delivery-admin
    ports:
      - "5174:80"
    depends_on:
      - backend
    restart: unless-stopped

  restaurant:
    build: ./restaurant
    container_name: drone-delivery-restaurant
    ports:
      - "5175:80"
    depends_on:
      - backend
    restart: unless-stopped
